/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.raven.form;

import com.raven.main.ConnectMySQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author doanq
 */
public class BeverageJP extends javax.swing.JPanel {

    /**
     * Creates new form BeverageJP
     */
    public BeverageJP() {
        initComponents();
        updateDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextSize = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrice = new javax.swing.JTextField();
        jButtonAddSize = new javax.swing.JButton();
        panelBorder2 = new com.raven.swing.PanelBorder();
        jLabel7 = new javax.swing.JLabel();
        spTable1 = new javax.swing.JScrollPane();
        tableBeverage = new com.raven.swing.Table();
        jLabel5 = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonReset = new javax.swing.JButton();
        jLabelSizeId = new javax.swing.JLabel();

        jLabel1.setText("Tên sản phẩm:");

        jLabel2.setText("Size:");

        jLabel3.setText("Giá tiền:");

        jButtonAddSize.setBackground(new java.awt.Color(204, 255, 204));
        jButtonAddSize.setText("Thêm size mới");
        jButtonAddSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddSizeActionPerformed(evt);
            }
        });

        panelBorder2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(127, 127, 127));
        jLabel7.setText(" Danh sách các sản phẩm");

        spTable1.setBorder(null);

        tableBeverage.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Mã size", "Loại (size)", "Giá tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBeverage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBeverageMouseClicked(evt);
            }
        });
        spTable1.setViewportView(tableBeverage);

        javax.swing.GroupLayout panelBorder2Layout = new javax.swing.GroupLayout(panelBorder2);
        panelBorder2.setLayout(panelBorder2Layout);
        panelBorder2Layout.setHorizontalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addComponent(spTable1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(panelBorder2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        panelBorder2Layout.setVerticalGroup(
            panelBorder2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBorder2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spTable1)
                .addContainerGap())
        );

        jLabel5.setText("Mã sản phẩm:");

        jLabelId.setBackground(new java.awt.Color(255, 255, 255));
        jLabelId.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jButtonAdd.setBackground(new java.awt.Color(102, 255, 102));
        jButtonAdd.setText("Thêm sản phẩm");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(255, 102, 102));
        jButtonDelete.setText("Xóa sản phẩm");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonEdit.setBackground(new java.awt.Color(255, 255, 153));
        jButtonEdit.setText("Chỉnh sửa sản phẩm");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonReset.setBackground(new java.awt.Color(242, 242, 242));
        jButtonReset.setText("Reset");
        jButtonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonResetActionPerformed(evt);
            }
        });

        jLabelSizeId.setForeground(new java.awt.Color(242, 242, 242));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonEdit)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonReset))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelId))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonAdd)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextFieldPrice)
                                        .addComponent(jTextSize, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAddSize))))
                    .addComponent(jLabelSizeId))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(panelBorder2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelId))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonAddSize)))
                .addGap(18, 18, 18)
                .addComponent(jLabelSizeId)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBorder2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
        insertBeverage();
        updateDB();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        deleteBeverage();
        updateDB();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        editBeverage();
        updateDB();
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonResetActionPerformed
        // TODO add your handling code here:
        updateDB();
        jLabelId.setText(null);
        jLabelSizeId.setText(null);
        jTextFieldName.setText(null);
        jTextSize.setText(null);
        jTextFieldPrice.setText(null);
    }//GEN-LAST:event_jButtonResetActionPerformed

    private void jButtonAddSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddSizeActionPerformed
        // TODO add your handling code here:
        jTextSize.setText("");
        jTextFieldPrice.setText("");
    }//GEN-LAST:event_jButtonAddSizeActionPerformed

    private void tableBeverageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBeverageMouseClicked
        // TODO add your handling code here:
        DefaultTableModel recordTable = (DefaultTableModel) tableBeverage.getModel();
        int selectionRow = tableBeverage.getSelectedRow();
        jLabelId.setText(recordTable.getValueAt(selectionRow, 0).toString());
        jTextFieldName.setText(recordTable.getValueAt(selectionRow, 1).toString());
        jLabelSizeId.setText(recordTable.getValueAt(selectionRow, 2).toString());
        jTextSize.setText(recordTable.getValueAt(selectionRow, 3).toString());
        jTextFieldPrice.setText(recordTable.getValueAt(selectionRow, 4).toString());
    }//GEN-LAST:event_tableBeverageMouseClicked
public void editBeverage() {
    try {
        Connection sqlConn = ConnectMySQL.ConnectMySQL();
        
        // Cập nhật thông tin của sản phẩm trong bảng beverage
        PreparedStatement pstBeverage = sqlConn.prepareStatement("UPDATE beverage SET name = ? WHERE id = ?");
        pstBeverage.setString(1, jTextFieldName.getText());
        pstBeverage.setInt(2, Integer.parseInt(jLabelId.getText()));
        pstBeverage.executeUpdate();
        
        // Nếu bạn muốn cập nhật các thuộc tính của sản phẩm cũng, bạn có thể thêm mã sau vào đây

        PreparedStatement pstProperties = sqlConn.prepareStatement("UPDATE properties SET size = ?, price = ? WHERE id = ?");
        pstProperties.setString(1, jTextSize.getText());
        pstProperties.setString(2, jTextFieldPrice.getText());
        pstProperties.setInt(3, Integer.parseInt(jLabelSizeId.getText()));
        pstProperties.executeUpdate();
        JOptionPane.showMessageDialog(this, "Đã chỉnh sửa sản phẩm " + jTextFieldName.getText());
        ConnectMySQL.closeConnection();
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(null, ex);
    }
}

    public void insertBeverage() {
        try {
            String msg = "Đã thêm một ";
            Connection sqlConn = ConnectMySQL.ConnectMySQL();

            // Kiểm tra xem tên sản phẩm đã tồn tại trong cơ sở dữ liệu chưa
            PreparedStatement pst1 = sqlConn.prepareStatement("SELECT * FROM beverage WHERE name = ?");
            pst1.setString(1, jTextFieldName.getText());
            ResultSet rs = pst1.executeQuery();

            if (rs.next()) {
                // Sản phẩm đã tồn tại, thêm thuộc tính mới cho sản phẩm
                PreparedStatement pst2 = sqlConn.prepareStatement("INSERT INTO properties (size, price, beverage) VALUES (?, ?, ?)");
                pst2.setString(1, jTextSize.getText());
                pst2.setString(2, jTextFieldPrice.getText());
                pst2.setInt(3, rs.getInt("id"));
                pst2.executeUpdate();
                msg += "loại sản phẩm mới";
            } else {
                // Sản phẩm chưa tồn tại, thêm sản phẩm mới và thuộc tính của nó
                PreparedStatement pstNew = sqlConn.prepareStatement("INSERT INTO beverage (name) VALUES (?)");
                pstNew.setString(1, jTextFieldName.getText());
                pstNew.executeUpdate();
                ResultSet generatedKeys = pstNew.getGeneratedKeys();
                int newBeverageId = 0;
                if (generatedKeys.next()) {
                    newBeverageId = generatedKeys.getInt(1);
                }
                PreparedStatement pstNewP = sqlConn.prepareStatement("INSERT INTO properties (size, price, beverage) VALUES (?, ?, ?)");
                pstNewP.setString(1, jTextSize.getText());
                pstNewP.setString(2, jTextFieldPrice.getText());
                pstNewP.setInt(3, newBeverageId);
                pstNewP.executeUpdate();
                msg += "sản phẩm và một loại sản phẩm mới";
            }
            ConnectMySQL.closeConnection();
            JOptionPane.showMessageDialog(this, msg);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void updateDB() {
        try {
            Connection sqlConn = ConnectMySQL.ConnectMySQL();
            PreparedStatement pst = sqlConn.prepareStatement("select b.id, b.name,p.size,p.price,p.id as size_id from beverage b join properties p where b.id=p.beverage");

            ResultSet rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            int q = stData.getColumnCount();
            DefaultTableModel recordTable = (DefaultTableModel) tableBeverage.getModel();
            recordTable.setRowCount(0);
            while (rs.next()) {
                Vector columnData = new Vector();
                for (int i = 1; i <= q; i++) {
                    columnData.add(rs.getString("id"));
                    columnData.add(rs.getString("name"));
                    columnData.add(rs.getString("size_id"));
                    columnData.add(rs.getString("size"));
                    columnData.add(rs.getString("price"));
                }
                recordTable.addRow(columnData);
            }
            ConnectMySQL.closeConnection();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void deleteBeverage() {
        try {
            Connection sqlConn = ConnectMySQL.ConnectMySQL();
            PreparedStatement pst = sqlConn.prepareStatement("delete from shift where id = ?");
            pst.setInt(1, Integer.parseInt(jLabelId.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(this, "Đã xóa một ca làm " + jTextFieldName.getText());
            ConnectMySQL.closeConnection();
            jLabelId.setText("");
            jTextFieldName.setText("");
            jTextSize.setText("");
            jTextFieldPrice.setText("");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonAddSize;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelSizeId;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldPrice;
    private javax.swing.JTextField jTextSize;
    private com.raven.swing.PanelBorder panelBorder2;
    private javax.swing.JScrollPane spTable1;
    private com.raven.swing.Table tableBeverage;
    // End of variables declaration//GEN-END:variables
}
